name: Surefile Report

on:
  push:
        

permissions:
  contents: read
  packages: write

jobs:
      
  Surefire-report:
    if: ${{ github.event.schedule || github.event.inputs.artifact == 'PPML-Scala-UT' || github.event.inputs.artifact == 'all' }} 
    runs-on: [ self-hosted, Gondolin, ubuntu-20.04-lts ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK8
        uses: ./.github/actions/jdk-setup-action
      - name: Set up maven
        uses: ./.github/actions/maven-setup-action
      # - name: Run test
      #   uses: ./.github/actions/ppml-scala-ut-action
      - name: Run tests
        run: |
            export SPARK_LOCAL_HOSTNAME=localhost
            export KERAS_BACKEND=tensorflow
            cd scala
            mvn "-DwildcardSuites=com.intel.analytics.bigdl.dllib.optim" "-Dtest=com.intel.analytics.bigdl.dllib.optim.*Test" test -P spark_3.x -Dspark.version=3.1.2
      
      - name: Publish Test Report
        # env:
        #   https_proxy: http://child-prc.intel.com:913
        #   http_proxy: http://child-prc.intel.com:913
        #   no_proxy: api.github.com
        if: ${{ always() }}
        uses: scacap/action-surefire-report@v1
        with:
          check_name: Example mvn Report
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: scala/dllib/target/surefire-reports/TEST*.xml
          
  
