name: Surefile Report

on:
  push:
    branches:    
    - 'wip/shaojun/test'
        


permissions:
  contents: read
  packages: write
  checks: write
  actions: write

jobs:
      
  Surefire-report:
    runs-on: [self-hosted, Gondolin-resources, ubuntu-20.04-lts]

    steps:
      - uses: actions/checkout@v3
      # - name: Create Awesome Badge
      #   uses: schneegans/dynamic-badges-action@v1.4.0
      #   with:
      #     auth: ${{ secrets.GIST_KEY }}
      #     gistID: 7495dccc42118020c12de5a095cfa2a6
      #     filename: test.json
      #     label: Hello
      #     message: World
      #     color: orange
      - name: Set up JDK8
        uses: ./.github/actions/jdk-setup-action
      - name: Set up maven
        uses: ./.github/actions/maven-setup-action
      - name: setup proxy
        run: |
          unset https_proxy
          unset http_proxy
          curl   -H "Accept: application/vnd.github+json"   -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"    https://api.github.com/repos/intel-analytics/BigDL/check-runs/8128386900
          # export no_proxy=api.github.com
      - name: Run test
        uses: ./.github/actions/ppml-scala-ut-action
      # - name: Run tests
      #   run: |
      #       export SPARK_LOCAL_HOSTNAME=localhost
      #       export KERAS_BACKEND=tensorflow
      #       cd scala
      #       mvn "-DwildcardSuites=com.intel.analytics.bigdl.dllib.optim" "-Dtest=com.intel.analytics.bigdl.dllib.optim.*Test" test -P spark_3.x -Dspark.version=3.1.2

      - name: Publish Test Report
        # env:
        #   https_proxy: http://child-prc.intel.com:913
        #   http_proxy: http://child-prc.intel.com:913
        #   no_proxy: api.github.com
        if: ${{ always() }}
        uses: scacap/action-surefire-report@v1
        with:
          check_name: Example mvn Report
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: scala/dllib/target/surefire-reports/TEST*.xml
          
  

